
import { Product, Order, User } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nitro Whey Isolate',
    brand: 'Nexus',
    price: 54.99,
    category: 'Protein',
    subCategory: 'Whey',
    images: ['https://images.unsplash.com/photo-1593095191850-2a0bf3a772bf?auto=format&fit=crop&q=80&w=800'],
    rating: 4.8,
    reviewCount: 156,
    description: 'Ultra-pure whey protein isolate for muscle recovery and growth.',
    warnings: ['Keep out of reach of children'],
    directions: 'Mix 1 scoop with 200ml water.',
    variants: ['Chocolate', 'Vanilla'],
    stock: 45,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Ferocious Pre-Workout',
    brand: 'Nexus',
    price: 110.00,
    category: 'Pre-Workout',
    subCategory: 'Focus',
    images: ['https://images.unsplash.com/photo-1579722820308-d74e5719d38f?auto=format&fit=crop&q=80&w=800'],
    rating: 4.5,
    reviewCount: 89,
    description: 'High-intensity formula to boost focus and energy.',
    warnings: ['High caffeine content'],
    directions: 'Take 1 scoop 30 mins before workout.',
    variants: ['Blue Razz'],
    stock: 12,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Syntha-6 Protein',
    brand: 'BSN',
    price: 40.00,
    category: 'Protein',
    subCategory: 'Blend',
    images: ['https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&q=80&w=800'],
    rating: 4.9,
    reviewCount: 230,
    description: 'Premium protein matrix for muscle support.',
    warnings: ['Contains milk and soy'],
    directions: 'Consume between meals or after workout.',
    variants: ['Cookies & Cream'],
    stock: 100,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Gorilla Mode',
    brand: 'Gorilla Mind',
    price: 50.00,
    category: 'Pre-Workout',
    subCategory: 'Pump',
    images: ['https://images.unsplash.com/photo-1616432043562-3671ea2e5242?auto=format&fit=crop&q=80&w=800'],
    rating: 4.7,
    reviewCount: 412,
    description: 'Maximalist pre-workout for massive pumps.',
    warnings: ['Do not exceed 2 scoops'],
    directions: 'Mix 1-2 scoops with water.',
    variants: ['Tiger Blood'],
    stock: 20,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Nutrex Mass Infusion',
    brand: 'Nutrex',
    price: 20.00,
    category: 'Wellness',
    subCategory: 'Gainer',
    images: ['https://images.unsplash.com/photo-1594882645126-14020914d58d?auto=format&fit=crop&q=80&w=800'],
    rating: 4.2,
    reviewCount: 64,
    description: 'Advanced weight gainer for rapid size increases.',
    warnings: ['Calorie dense'],
    directions: 'Mix 4 scoops with 600ml milk.',
    variants: ['Vanilla'],
    stock: 15,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Omega-3 Gold',
    brand: 'Nexus',
    price: 24.99,
    category: 'Vitamins',
    subCategory: 'Health',
    images: ['https://images.unsplash.com/photo-1626202340516-906b23750841?auto=format&fit=crop&q=80&w=800'],
    rating: 5.0,
    reviewCount: 120,
    description: 'Triple-strength fish oil for heart and brain health.',
    warnings: ['Fish allergy alert'],
    directions: 'Take 1 softgel daily with a meal.',
    variants: ['Lemon'],
    stock: 60,
    isActive: true,
    reviews: [],
    cartItems: [],
    wishlist: [],
    orderItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    date: '2023-10-25',
    customerName: 'Operative Alpha',
    customerEmail: 'alpha@nexus.com',
    total: 89.98,
    status: 'Shipped',
    items: [
      { productName: 'Nitro Whey Isolate', quantity: 1, price: 54.99 },
      { productName: 'Ferocious Pre-Workout', quantity: 1, price: 34.99 }
    ]
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Commander Admin',
    email: 'admin@nexus.com',
    role: 'ADMIN',
    status: 'Active',
    joinDate: '2023-01-01'
  },
];
